services:
  kostal-ms:
    build: .
    image: ghcr.io/voltcast-a-ase-project/kostal-microservice/kostal-ms:latest
    networks:
      - VoltCast_Network
    ports:
      - "8082:8082"
    expose:
      - "8082"

networks:
  VoltCast_Network:
    external: true